global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'service-voiture'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8081']
        labels:
          service: 'service-voiture'
  
  - job_name: 'service-client'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8082']
        labels:
          service: 'service-client'
